mod auth_packet;
mod hex;
mod utils;

use aes_gcm::KeyInit;
use ed25519_dalek::ed25519::signature::SignerMut;
use hex::to_hex;
use protocol::e2e_packet;
use rand::Rng;
use std::convert::TryInto;
use std::{cell::RefCell, collections::HashMap};
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn main() {
    utils::set_panic_hook();

    // other init logic
}

thread_local! {
    static STATE: RefCell<MyState> = RefCell::new(MyState::default());
}

fn timestamp() -> Result<u64, String> {
    Ok(web_time::SystemTime::now()
        .duration_since(web_time::SystemTime::UNIX_EPOCH)
        .map_err(|_| "failed to get unix time")?
        .as_millis() as u64)
}

#[derive(Default)]
struct MyState {
    pub sign_key: Option<ed25519_dalek::SigningKey>,
    pub ver_key: Option<ed25519_dalek::VerifyingKey>,
    pub chats: HashMap<u64, Chat>,
}

enum Chat {
    /// Only used from the client's perspective.
    Syn {
        server_ver_key: ed25519_dalek::VerifyingKey,
        client_eph_priv_key: x25519_dalek::EphemeralSecret,
        syn_digest: [u8; 32],
    },

    /// Used after encrypted connection has been established.
    Encrypted {
        cipher: aes_gcm::Aes256Gcm,
        other_ver_key: ed25519_dalek::VerifyingKey,
        messages: Vec<Message>,
    },
}

#[derive(serde::Serialize)]
enum Message {
    ToOther(protocol::e2e_packet::raw::DecryptedMessagePayload),
    ToSelf(protocol::e2e_packet::raw::DecryptedMessagePayload),
    System(String),
}

#[derive(serde::Serialize)]
struct MessageUpdateToFrontend {
    chat_id: String,
    message: Message,
}

/// Establishes a connection with a proxy by signing a server-generated random value.
/// This function retrieves the signing key and verifying key from the internal state,
/// signs the provided random value, and constructs an authentication packet.
/// The authentication packet is serialized into a JSON string and returned.
///
/// # Arguments
///
/// * `proxy_random` - A vector of bytes representing the random value generated by the server.
///
/// # Returns
///
/// * `Result<String, String>` - On success, returns a JSON string of the authentication packet.
///   On failure, returns an error message.

#[wasm_bindgen]
pub fn proxy_connect(proxy_random: Vec<u8>) -> Result<String, String> {
    STATE.with(|state| {
        let state = state.borrow_mut();
        let mut sign_key = state.sign_key.as_ref().ok_or("no sign key")?.clone();
        let ver_key = state.ver_key.as_ref().ok_or("no ver key")?;

        // Sign the proxy random.
        let sig = sign_key.sign(&proxy_random);

        let auth_packet = auth_packet::AuthPacket {
            ver_key: *ver_key,
            signature: sig,
        };

        serde_json::to_string(&auth_packet).map_err(|e| e.to_string())
    })
}

/// Generates a keypair and stores the public and private key in the internal state.
/// Returns an array with two elements: the first is the private key, and the second is
/// the public key.

#[wasm_bindgen]
pub fn make_keypair() -> Result<js_sys::Array, JsValue> {
    let mut rng = rand::thread_rng();
    let sign_key = ed25519_dalek::SigningKey::generate(&mut rng);
    let ver_key = sign_key.verifying_key();

    // Store
    STATE.with(|state| {
        let mut state = state.borrow_mut();
        state.sign_key = Some(sign_key.clone());
        state.ver_key = Some(ver_key);
    });

    let arr = js_sys::Array::new();
    arr.push(&serde_wasm_bindgen::to_value(
        &sign_key.to_bytes().to_vec(),
    )?);
    arr.push(&serde_wasm_bindgen::to_value(&ver_key.to_bytes().to_vec())?);
    Ok(arr)
}

/// Loads a sign key and verifying key from the given byte arrays into the internal state.
/// Returns the loaded keypair as an array with two elements: the first is the private key, and the second is
/// the public key.
#[wasm_bindgen]
pub fn load_sign_key(sign_key: Vec<u8>) -> Result<js_sys::Array, JsValue> {
    let sign_key_arr: [u8; 32] = sign_key
        .as_slice()
        .try_into()
        .map_err(|_| JsValue::from_str("invalid sign key length"))?;
    let sign_key = ed25519_dalek::SigningKey::from_bytes(&sign_key_arr);
    let ver_key = sign_key.verifying_key();
    STATE.with(|state| {
        let mut state = state.borrow_mut();
        state.sign_key = Some(sign_key.clone());
        state.ver_key = Some(ver_key);
    });
    let arr = js_sys::Array::new();
    arr.push(&serde_wasm_bindgen::to_value(
        &sign_key.to_bytes().to_vec(),
    )?);
    arr.push(&serde_wasm_bindgen::to_value(&ver_key.to_bytes().to_vec())?);
    Ok(arr)
}

#[derive(serde::Serialize)]
struct InitChatReturnValue {
    message_updates: Vec<MessageUpdateToFrontend>,
    packet: String, // serialized to json
}

#[wasm_bindgen]
pub fn init_chat(server_ver_key: Vec<u8>) -> Result<String, JsValue> {
    STATE.with(|state| -> Result<String, JsValue> {
        let mut state = state.borrow_mut();

        let mut sign_key = state
            .sign_key
            .as_ref()
            .ok_or(JsValue::from_str("no sign key"))?
            .clone();

        let mut rng = rand::thread_rng();
        let client_random = rng.gen::<[u8; 32]>();
        let id = rng.gen::<u64>();
        let server_ver_key_arr: [u8; 32] = server_ver_key
            .as_slice()
            .try_into()
            .map_err(|_| JsValue::from_str("invalid server ver key length"))?;
        let server_ver_key = ed25519_dalek::VerifyingKey::from_bytes(&server_ver_key_arr)
            .map_err(|_| JsValue::from_str("invalid server ver key"))?;
        let eph_priv_key = x25519_dalek::EphemeralSecret::random_from_rng(rng);
        let eph_pub_key = x25519_dalek::PublicKey::from(&eph_priv_key);
        let syn = e2e_packet::raw::SYN::new(
            &mut sign_key,
            eph_pub_key,
            server_ver_key,
            client_random,
            timestamp()?,
            id,
        );
        state.chats.insert(
            id,
            Chat::Syn {
                server_ver_key,
                client_eph_priv_key: eph_priv_key,
                syn_digest: syn.digest(),
            },
        );

        let packet = e2e_packet::E2EPacket::SYN(Box::new(syn));
        let packet_json = serde_json::to_string(&packet).unwrap();

        let json = serde_json::to_string(&InitChatReturnValue {
            message_updates: vec![MessageUpdateToFrontend {
                chat_id: id.to_string(),
                message: Message::System(format!(
                    "Initializing chat {} with {}",
                    id,
                    to_hex(&server_ver_key.to_bytes())
                )),
            }],
            packet: packet_json,
        })
        .map_err(|_| JsValue::from_str("failed to serialize json"))?;

        Ok(json)
    })
}

#[derive(serde::Serialize)]
struct ReadPacketReturnValue {
    message_updates: Vec<MessageUpdateToFrontend>,
    packet: Option<String>,
}

#[wasm_bindgen]
pub fn read_packet(packet: String) -> Result<String, JsValue> {
    STATE.with(|state| -> Result<String, JsValue> {
        let packet: e2e_packet::E2EPacket = serde_json::from_str(&packet).unwrap();
        let mut state = state.borrow_mut();
        let mut message_updates = Vec::new();

        let mut sign_key = state
            .sign_key
            .as_ref()
            .ok_or(JsValue::from_str("no sign key"))?.clone();
        #[allow(clippy::clone_on_copy)]
        let ver_key = state
            .ver_key
            .as_ref()
            .ok_or(JsValue::from_str("no ver key"))?.clone();

        let response_packet: Option<String> = 'packet: {
            match packet {
                e2e_packet::E2EPacket::SYN(packet) => {
                    if state.chats.contains_key(&packet.id) {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("New SYN packet for this chat allegedly from {}", to_hex(&packet.client_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    }

                    if let Err(e) = packet.verify_signature() {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} allegedly tried to start chat {} but signature was invalid: {}", to_hex(&packet.client_ver_key.to_bytes()) , packet.id, e)),
                        });
                        break 'packet None;
                    }

                    if packet.server_ver_key != *state.ver_key.as_ref().unwrap() {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to start chat but recipient does not match ({})", to_hex(&packet.client_ver_key.to_bytes()), to_hex(&packet.server_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    }

                    if packet.timestamp + 5000 < timestamp()? {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} allegedly tried to start chat {} but timestamp was too old", to_hex(&packet.client_ver_key.to_bytes()), packet.id)),
                        });
                        break 'packet None;
                    }

                    let mut rng = rand::thread_rng();
                    let server_random = rng.gen::<[u8; 32]>();
                    let eph_priv_key = x25519_dalek::EphemeralSecret::random_from_rng(rng);
                    let eph_pub_key = x25519_dalek::PublicKey::from(&eph_priv_key);

                    let ack = e2e_packet::raw::ACK::new(packet.id, packet.digest(), &mut sign_key, ver_key, packet.client_ver_key, eph_pub_key, server_random);

                    let shared_secret = eph_priv_key.diffie_hellman(&packet.client_eph_pub_key);

                    let cipher = aes_gcm::Aes256Gcm::new(aes_gcm::Key::<aes_gcm::Aes256Gcm>::from_slice(&shared_secret.as_bytes()[0..32]));

                    state.chats.insert(
                        packet.id,
                        Chat::Encrypted {
                            cipher,
                            other_ver_key: packet.client_ver_key,
                            messages: Vec::new(),
                        },
                    );

                    let response_packet = e2e_packet::E2EPacket::ACK(ack);
                    let response_packet_json = serde_json::to_string(&response_packet).unwrap();

                    message_updates.push(MessageUpdateToFrontend {
                        chat_id: packet.id.to_string(),
                        message: Message::System(format!("{} initiated chat {}", to_hex(&packet.client_ver_key.to_bytes()), packet.id)),
                    });

                    Some(response_packet_json)
                }
                e2e_packet::E2EPacket::ACK(packet) => {
                    let ( server_ver_key, client_eph_priv_key, syn_digest) = if let Some(chat) = state.chats.get_mut(&packet.id) {
                        if let Chat::Syn { server_ver_key, client_eph_priv_key, syn_digest } = chat {
                            // Take ownership of the ephemeral secret so we can call diffie_hellman
                            (
                                *server_ver_key,
                                std::mem::replace(client_eph_priv_key, x25519_dalek::EphemeralSecret::random_from_rng(rand::thread_rng())),
                                *syn_digest
                            )
                        } else {
                            message_updates.push(MessageUpdateToFrontend {
                                chat_id: packet.id.to_string(),
                                message: Message::System(format!("{} attempted to acknowledge but connection is already established", to_hex(&packet.client_ver_key.to_bytes()))),
                            });
                            break 'packet None;
                        }
                    } else {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to acknowledge but chat does not exist", to_hex(&packet.client_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    };

                    if let Err(e) = packet.verify_signature() {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to acknowledge but signature was invalid: {}", to_hex(&packet.client_ver_key.to_bytes()), e)),
                        });
                        break 'packet None;
                    }
                    if packet.client_ver_key != ver_key {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to acknowledge but recipient does not match", to_hex(&packet.client_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    }

                    if syn_digest != packet.syn_digest {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to acknowledge but syn_digest was wrong", to_hex(&packet.client_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    }

                    if server_ver_key != packet.server_ver_key {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to acknowledge but server_ver_key was wrong", to_hex(&packet.client_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    }

                    let shared_secret = client_eph_priv_key.diffie_hellman(&packet.server_eph_pub_key);

                    let cipher = aes_gcm::Aes256Gcm::new(aes_gcm::Key::<aes_gcm::Aes256Gcm>::from_slice(&shared_secret.as_bytes()[0..32]));

                    state.chats.insert(
                        packet.id,
                        Chat::Encrypted {
                            cipher,
                            other_ver_key: packet.server_ver_key,
                            messages: Vec::new(),
                        },
                    );

                    message_updates.push(MessageUpdateToFrontend {
                        chat_id: packet.id.to_string(),
                        message: Message::System(format!("{} acknowledged chat {}", to_hex(&packet.server_ver_key.to_bytes()), packet.id)),
                    });

                    None
                },
                e2e_packet::E2EPacket::EncryptedMessage(packet) => {
                    // Only borrow chats mutably for the minimum scope necessary
                    let (cipher, other_ver_key, messages) = {
                        if let Some(chat) = state.chats.get_mut(&packet.id) {
                            if let Chat::Encrypted { cipher, other_ver_key, messages } = chat {
                                (cipher, other_ver_key, messages)
                            } else {
                                message_updates.push(MessageUpdateToFrontend {
                                    chat_id: packet.id.to_string(),
                                    message: Message::System(format!("{} attempted to send message but connection is not established", to_hex(&packet.sender_ver_key.to_bytes()))),
                                });
                                break 'packet None;
                            }
                        } else {
                            message_updates.push(MessageUpdateToFrontend {
                                chat_id: packet.id.to_string(),
                                message: Message::System(format!("{} attempted to send message but chat does not exist", to_hex(&packet.sender_ver_key.to_bytes()))),
                            });
                            break 'packet None;
                        }
                    };

                    // No need to verify the signature because AES-GCM will fail if the message is tampered with

                    if *other_ver_key != packet.sender_ver_key {
                        message_updates.push(MessageUpdateToFrontend {
                            chat_id: packet.id.to_string(),
                            message: Message::System(format!("{} attempted to send message but sender_ver_key was wrong", to_hex(&packet.sender_ver_key.to_bytes()))),
                        });
                        break 'packet None;
                    }

                    let message = match packet.message.decrypt(cipher, packet.nonce) {
                        Ok(message) => message,
                        Err(e) => {
                            message_updates.push(MessageUpdateToFrontend {
                                chat_id: packet.id.to_string(),
                                message: Message::System(format!("{} attempted to send message but decryption failed: {}", to_hex(&packet.sender_ver_key.to_bytes()), e)),
                            });
                            break 'packet None;
                        }
                    };

                    messages.push(Message::ToSelf(message.clone()));

                    message_updates.push(MessageUpdateToFrontend {
                        chat_id: packet.id.to_string(),
                        message: Message::ToSelf(message),
                    });

                    None
                }
            }
        };

        let rv = ReadPacketReturnValue {
            message_updates,
            packet: response_packet,
        };

        let rv = serde_json::to_string(&rv).map_err(|e| e.to_string())?;
        Ok(rv)
    })
}

#[wasm_bindgen]
pub fn send_message(message: String, chat_id: u64) -> Result<String, String> {
    STATE.with(|state| {
        let mut state = state.borrow_mut();

        #[allow(clippy::clone_on_copy)]
        let ver_key = state.ver_key.as_ref().ok_or("no ver key")?.clone();
        let sign_key = state.sign_key.as_ref().ok_or("no sign key")?.clone();

        let concat = state
            .chats
            .keys()
            .fold(String::new(), |acc, k| format!("{acc} {k}"));
        let chat = state
            .chats
            .get_mut(&chat_id)
            .ok_or(format!("chat does not exist: {concat}: {chat_id}"))?;

        let (cipher, other_ver_key, messages) = if let Chat::Encrypted {
            cipher,
            other_ver_key,
            messages,
        } = chat
        {
            (cipher, other_ver_key, messages)
        } else {
            return Err("chat is not encrypted".to_string());
        };

        let index = messages
            .iter()
            .rev()
            .find_map(|msg| match msg {
                Message::ToOther(msg) => Some(msg.id),
                _ => None,
            })
            .unwrap_or(0);

        let decrypted_payload = e2e_packet::raw::DecryptedMessagePayload {
            id: index + 1,
            content: message,
        };

        let encrypted_packet = e2e_packet::raw::EncryptedMessage::new(
            chat_id,
            ver_key,
            *other_ver_key,
            &decrypted_payload,
            cipher,
            &mut sign_key.clone(),
        )
        .map_err(|e| format!("Encryption failed: {e:?}"))?;

        messages.push(Message::ToOther(decrypted_payload));

        let packet = e2e_packet::E2EPacket::EncryptedMessage(encrypted_packet);

        let packet = serde_json::to_string(&packet).map_err(|e| e.to_string())?;
        Ok(packet)
    })
}
